[project]
name = "seattle"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "duckdb>=1.4.2",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pandas-stubs==2.3.2.250926",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
